import vm from 'node:vm';import fs from 'node:fs';import crypto from 'node:crypto';
export function gasFixture(){
 const failures={writeAt:0,count:0};
 class Sheet {constructor(name,values){this.name=name;this.values=structuredClone(values);this.formulas=[];this.max=1000;}
 getParent(){return ss;}getName(){return this.name;}getMaxRows(){return this.max;}insertRowsAfter(n,count){this.max+=count;}hideSheet(){}getLastRow(){let n=this.values.length;while(n>0&&this.values[n-1].every(x=>x===''))n--;return n;}getDataRange(){return {getValues:()=>structuredClone(this.values),getFormulas:()=>this.values.map((r,i)=>r.map((_,j)=>this.formulas[i]?.[j]||''))};}
 appendRow(r){this.values.push(r);return this;}getRange(row,col,n=1,m=1){return {getValues:()=>Array.from({length:n},(_,i)=>Array.from({length:m},(_,j)=>this.values[row+i-1]?.[col+j-1]??'')),setValue:v=>this.getRange(row,col).setValues([[v]]),setValues:rows=>{if(this.name!=='_Admin Journal'){failures.count++;if(failures.writeAt===failures.count)throw Error('simulated write interruption');}rows.forEach((r,i)=>{while(this.values.length<row+i)this.values.push(Array(this.values[0].length).fill(''));r.forEach((v,j)=>this.values[row+i-1][col+j-1]=v);});return this;}};}
 deleteRows(start,n){this.values.splice(start-1,n);}
 }
 const props={ADMIN_EMAILS:'owner@gmail.com',ADMIN_GATEWAY_SECRET:'s'.repeat(64),SPREADSHEET_ID:'test'};const sheets={};const ss={getSheetByName:n=>sheets[n],getSpreadsheetTimeZone:()=> 'Africa/Tunis',insertSheet:n=>sheets[n]=new Sheet(n,[])};
 const ctx={console:{log(){},warn(){},error(){}},Date,Intl,JSON,URL,Set,Map,PropertiesService:{getScriptProperties:()=>({getProperty:k=>props[k],setProperty:(k,v)=>props[k]=v})},SpreadsheetApp:{openById:()=>ss,getActiveSpreadsheet:()=>ss,flush(){}},Session:{getScriptTimeZone:()=> 'Africa/Tunis'},LockService:{getScriptLock:()=>({waitLock(){},releaseLock(){}})},Utilities:{Charset:{UTF_8:'utf8'},DigestAlgorithm:{SHA_256:'sha256'},getUuid:()=>crypto.randomUUID(),formatDate:(d,tz,fmt)=>fmt==='yyyy-MM-dd'?new Date(d).toISOString().slice(0,10):new Date(d).toISOString().replace(/[-:TZ.]/g,'').slice(0,15),computeDigest:(_,s)=>Array.from(crypto.createHash('sha256').update(s).digest()),computeHmacSha256Signature:(s,k)=>Array.from(crypto.createHmac('sha256',k).update(s).digest())},ContentService:{MimeType:{JSON:'json'},createTextOutput:s=>({text:s,setMimeType(){return this;}})},MailApp:{sendEmail(){throw Error('TEST MUST NEVER SEND EMAIL');}},UrlFetchApp:{fetch(){throw Error('TEST MUST NEVER CALL EXTERNAL API');}}};
 vm.createContext(ctx);for(const name of ['Domain.gs','Admin.gs','Code.gs'])vm.runInContext(fs.readFileSync('apps-script/'+name,'utf8'),ctx);
 const HEADERS=vm.runInContext('HEADERS',ctx);for(const [key,name] of Object.entries({products:'Products',variants:'Variants',orders:'Orders',orderItems:'Order Items'}))sheets[name]=new Sheet(name,[Array.from(HEADERS[key])]);
 function add(name,obj){const headers=sheets[name].values[0];sheets[name].values.push(headers.map(h=>obj[h]??''));}
 ctx.sendOrderInvoiceSafely_=()=>true;ctx.notifyAdminNewOrder_=()=>true; // Isolate all outgoing email paths.
 function call(body){const message=JSON.stringify({email:'owner@gmail.com',sub:'1',iat:Math.floor(Date.now()/1000),exp:Math.floor(Date.now()/1000)+90,body}),signature=crypto.createHmac('sha256',props.ADMIN_GATEWAY_SECRET).update(message).digest('hex');return JSON.parse(ctx.handleAdminRequest_({message,signature}).text);}
 return {ctx,sheets,ss,props,failures,add,call,revision:()=>ctx.adminRevision_(ctx.adminTables_(ss)),Sheet};
}
