import test from 'node:test';import assert from 'node:assert/strict';import {gasFixture} from './gas-fixture.mjs';
const product={name:'Chargeur rapide',category:'Téléphonie',price:29.9,stock:12,image:'https://a.test/img.webp',description:'<p>Test</p>',images:['https://a.test/w_400,q_auto/a.webp'],variants:[{color:'Noir',size:'M',price:0,stock:6,active:true}]};
function setup(){const f=gasFixture();f.ctx.setupKlyvoAdmin();return f;}
function save(f,p=product,id='adm-1234567890123456'){return {action:'saveProduct',product:p,requestId:id,revision:f.revision()};}
test('save and retry writes one product and one variant; IDs immutable on edit',()=>{const f=setup(),req=save(f);let r=f.call(req);assert.equal(r.success,true,r.message);const id=r.data.id;assert.equal(f.call(req).success,true);assert.equal(f.sheets.Products.getLastRow(),2);assert.equal(f.sheets.Variants.getLastRow(),2);let snap=f.call({action:'snapshot'}).data;assert.equal(snap.products[0].images[0],product.images[0]);const p=snap.products[0],sku=p.sku,vid=p.variants[0].id;p.name='Autre nom';p.sku='FORGED';p.variants[0].sku='FORGED';r=f.call(save(f,p,'adm-2234567890123456'));assert.equal(r.success,true,r.message);snap=f.call({action:'snapshot'}).data;assert.equal(snap.products[0].sku,sku);assert.equal(snap.products[0].variants[0].id,vid);assert.notEqual(snap.products[0].variants[0].sku,'FORGED');assert.equal(snap.products[0].id,id);});
test('concurrent storefront stock update rejects stale editor revision',()=>{const f=setup();f.call(save(f));const snap=f.call({action:'snapshot'}).data;const req={...save(f,snap.products[0],'adm-3234567890123456'),revision:snap.revision};f.sheets.Variants.values[1][7]=2;const r=f.call(req);assert.equal(r.success,false);assert.match(r.message,/Conflit/);assert.equal(f.sheets.Variants.values[1][7],2);});
test('historical products archive, nonhistorical delete keeps other physical rows',()=>{const f=setup();f.call(save(f));const p=f.call({action:'snapshot'}).data.products[0];f.add('Order Items',{'Order Item ID':'item','Order ID':'ord','Product ID':p.id});let r=f.call({action:'deleteProduct',id:p.id,mode:'delete',requestId:'adm-4234567890123456',revision:f.revision()});assert.equal(r.success,true,r.message);assert.equal(r.data.archived,true);assert.equal(f.sheets.Products.values[1][20],false);assert.equal(f.sheets['Order Items'].getLastRow(),2);});
test('mid-save failure compensates earlier writes and records rollback',()=>{const f=setup();f.failures.writeAt=2;const r=f.call(save(f));assert.equal(r.success,false);assert.ok(f.sheets.Products.values[1].every(x=>x===''));assert.equal(f.sheets['_Admin Journal'].values[1][1],'ROLLED_BACK');});
test('checkout with blank rows decrements correct variant and deduplicates request',()=>{const f=setup();f.add('Products',{'Product ID':'p','Product Name':'Test','Active':true,'Regular Price TND':20,'Stock':10});f.sheets.Variants.values.push(Array(9).fill(''));f.add('Variants',{'Variant ID':'v','Product ID':'p','Color':'Noir','Variant Price TND':0,'Variant Stock':7,'Active':true});const request={requestId:'req-1234567890123456',customer:{name:'Test User',email:'test@example.com',phone:'20123456',address:'Test address',city:'Tunis',postalCode:'1000',paymentMethod:'Paiement à la livraison'},items:[{productId:'p',color:'Noir',size:'',quantity:2}]};const r=f.ctx.createOrder_(request);assert.equal(r.subtotal,40);assert.equal(f.sheets.Variants.values[2][7],5);assert.ok(f.sheets.Variants.values[1].every(x=>x===''));assert.equal(f.ctx.createOrder_(request).duplicate,true);assert.equal(f.sheets.Variants.values[2][7],5);});
test('pending journal freezes checkout before any inventory changes',()=>{const f=setup();f.sheets['_Admin Journal'].appendRow(['adm-x','PENDING']);assert.throws(()=>f.ctx.adminAssertNoPending_(),/réconcilier/);});
test('deleted highest product ID is never recycled for a new product',()=>{const f=setup();const a=f.call(save(f)).data;f.call({action:'deleteProduct',id:a.id,mode:'delete',requestId:'adm-5234567890123456',revision:f.revision()});const b=f.call(save(f,product,'adm-6234567890123456')).data;assert.notEqual(a.id,b.id);});
test('empty numeric strings and malformed variants cannot zero stock silently',()=>{const f=setup();assert.equal(f.call(save(f,{...product,variants:[{color:'Noir',stock:'',price:0}]})).success,false);});
